apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: default
  name: kaixin-gateway
  labels:
    app: kaixin-gateway
spec:
  selector:
    matchLabels:
      app: kaixin-gateway
  template:
    metadata:
      labels:
        app: kaixin-gateway
    spec:
      serviceAccountName: kaixin-gateway-sa
      containers:
        - name: kaixin-gateway
          imagePullPolicy: Always
          image: k3d-kaixin-registry:12345/gateway:v1.0
          ports:
            - containerPort: 8085
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: kaixin-gateway-service
spec:
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      nodePort: 32005
  selector:
    app: kaixin-gateway
  sessionAffinity: None

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaixin-gateway-sa
  namespace: default

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: service-reader
rules:
  - apiGroups: [""]  # Core API group
    resources: ["services"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["networking.k8s.io"]  # Correct API group for Ingresses
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaixin-gateway-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: kaixin-gateway-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io